### ISSUE TITLE
Unable to create session cookie

### ISSUE THREAD

**Issue by diefans** [chmike/securecookie#19] opened 2021-03-08 17:09 UTC
To me it seems due to the fact, that `Obj.MaxAge` cannot be ommited despite it is optional, it is impossible to create a session cookie: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#attributes

**Comment by chmike** [comment] 2021-03-08 19:25
Could you tell me if the problem is on the side of the client or this module ? As I understand your comment, the problem seam to be on the client side and not this module. In this case I can’t help.

**Comment by chmike** [comment] 2021-03-11 08:46
When MaxAge is 0, the MaxAge field is not added to the HTTP header. You then should have a session cookie. If this fails, I need to get more information on what happens. What fails, how it fails, what component report an error, the error message, etc.

**Comment by chmike** [comment] 2021-03-11 14:55
I tested with a small test program and there is indeed an error with the secure cookie when MaxAge is 0. The error occurs when decoding the cookie. The current code claim that, the time stamp value is invalid. I’ll fix the code and provide a new release ASAP.

**Comment by chmike** [comment] 2021-03-11 15:29
The problem is fixed in the release v1.3.1. It is now possible to create a session cookie and read it back without error.

**Closed by chmike** 2021-03-11 15:29 UTC
